"""Module containing the maps of the different rooms."""

ROOM_ONE = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]

ROOM_TWO = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                              X",
    "X                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                              X",
    "X                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                              X",
    "X                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                              X",
    "X                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                    X",
    "X                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                    X",
    "X                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                    X",
    "X                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                    X",
    "X                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                    X",
    "X                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                    X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]
