"""Module containing the maps of the different rooms."""

ROOM_ONE = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXD00D00XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]

ROOM_TWO = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                    XXXXXXXXXXXX                                                                           XXX",
    "XXX                                    XXXXXXXXXXXX                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                    XXXXXXXXXXXX                                                                           XXX",
    "XXX                                    XXXXXXXXXXXX                                                                           XXX",
    "XXX                                    XXXXXXXXXXXX                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXX                                                                                                                           XXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXD00D00XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]
