"""Module containing the maps of the different rooms."""

ROOM_TEST = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX                                                                                                            X",
    "XXXXXXXXXXXXXXXXXX                                                                                                             X",
    "XXXXXXXXXXXXXXXXX                                                                                                              X",
    "XXXXXXXXXXXXXXXX                                                                                                               X",
    "XXXXXXXXXXXXXXX                                                                                                                X",
    "XXXXXXXXXXXXX                                                                                                                  X",
    "XXXXXXXXXXXX                                                                                                                   X",
    "XXXXXXXXXXX                                                                                                                    X",
    "XXXXXXXXXX                                                                                                                     X",
    "XXXXXXXXX                                                                                                                      X",
    "XXXXXXXX                                                                                                                       X",
    "XXXXXX                                                                                                                         X",
    "XXXX                                                                                                                           X",
    "XXX                                                                                                                            X",
    "XX                                                                                                                             X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "X                                                                                                                              X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]
